/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIdRouteImport } from './routes/resources.$id'
import { Route as AdminReadinessRouteImport } from './routes/admin.readiness'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminPackingRouteImport } from './routes/admin.packing'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminJourneyRouteImport } from './routes/admin.journey'
import { Route as AdminGoalsRouteImport } from './routes/admin.goals'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminFamilyRouteImport } from './routes/admin.family'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminConciergeRouteImport } from './routes/admin.concierge'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResourcesRoute,
} as any)
const AdminReadinessRoute = AdminReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackingRoute = AdminPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJourneyRoute = AdminJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoalsRoute = AdminGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFamilyRoute = AdminFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConciergeRoute = AdminConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/mcp': typeof McpRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signin': typeof SigninRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/journey': typeof AdminJourneyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packing': typeof AdminPackingRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/mcp': typeof McpRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signin': typeof SigninRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/journey': typeof AdminJourneyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packing': typeof AdminPackingRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/mcp': typeof McpRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/signin': typeof SigninRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/journey': typeof AdminJourneyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packing': typeof AdminPackingRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/confirmation'
    | '/dashboard'
    | '/expenses'
    | '/family'
    | '/mcp'
    | '/packing'
    | '/profile'
    | '/register'
    | '/resources'
    | '/signin'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/announcements'
    | '/admin/concierge'
    | '/admin/contacts'
    | '/admin/family'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/goals'
    | '/admin/journey'
    | '/admin/notifications'
    | '/admin/packing'
    | '/admin/participants'
    | '/admin/readiness'
    | '/resources/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/confirmation'
    | '/dashboard'
    | '/expenses'
    | '/family'
    | '/mcp'
    | '/packing'
    | '/profile'
    | '/register'
    | '/resources'
    | '/signin'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/announcements'
    | '/admin/concierge'
    | '/admin/contacts'
    | '/admin/family'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/goals'
    | '/admin/journey'
    | '/admin/notifications'
    | '/admin/packing'
    | '/admin/participants'
    | '/admin/readiness'
    | '/resources/$id'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/confirmation'
    | '/dashboard'
    | '/expenses'
    | '/family'
    | '/mcp'
    | '/packing'
    | '/profile'
    | '/register'
    | '/resources'
    | '/signin'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/announcements'
    | '/admin/concierge'
    | '/admin/contacts'
    | '/admin/family'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/goals'
    | '/admin/journey'
    | '/admin/notifications'
    | '/admin/packing'
    | '/admin/participants'
    | '/admin/readiness'
    | '/resources/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ConfirmationRoute: typeof ConfirmationRoute
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  FamilyRoute: typeof FamilyRoute
  McpRoute: typeof McpRoute
  PackingRoute: typeof PackingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SigninRoute: typeof SigninRoute
  TeamRoute: typeof TeamRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/admin/readiness': {
      id: '/admin/readiness'
      path: '/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AdminReadinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packing': {
      id: '/admin/packing'
      path: '/packing'
      fullPath: '/admin/packing'
      preLoaderRoute: typeof AdminPackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/journey': {
      id: '/admin/journey'
      path: '/journey'
      fullPath: '/admin/journey'
      preLoaderRoute: typeof AdminJourneyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/goals': {
      id: '/admin/goals'
      path: '/goals'
      fullPath: '/admin/goals'
      preLoaderRoute: typeof AdminGoalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/family': {
      id: '/admin/family'
      path: '/family'
      fullPath: '/admin/family'
      preLoaderRoute: typeof AdminFamilyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/concierge': {
      id: '/admin/concierge'
      path: '/concierge'
      fullPath: '/admin/concierge'
      preLoaderRoute: typeof AdminConciergeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminConciergeRoute: typeof AdminConciergeRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminFamilyRoute: typeof AdminFamilyRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminGoalsRoute: typeof AdminGoalsRoute
  AdminJourneyRoute: typeof AdminJourneyRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackingRoute: typeof AdminPackingRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminReadinessRoute: typeof AdminReadinessRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminConciergeRoute: AdminConciergeRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminFamilyRoute: AdminFamilyRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminGoalsRoute: AdminGoalsRoute,
  AdminJourneyRoute: AdminJourneyRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackingRoute: AdminPackingRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminReadinessRoute: AdminReadinessRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResourcesRouteChildren {
  ResourcesIdRoute: typeof ResourcesIdRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesIdRoute: ResourcesIdRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ConfirmationRoute: ConfirmationRoute,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  FamilyRoute: FamilyRoute,
  McpRoute: McpRoute,
  PackingRoute: PackingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SigninRoute: SigninRoute,
  TeamRoute: TeamRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
