/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RiderProgressRouteImport } from './routes/rider-progress'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FundraiserRequestRouteImport } from './routes/fundraiser-request'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CaptainsLoungeRouteImport } from './routes/captains-lounge'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as MyFundraisersIndexRouteImport } from './routes/my-fundraisers.index'
import { Route as FundraisersIndexRouteImport } from './routes/fundraisers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorsNewRouteImport } from './routes/vendors.new'
import { Route as VendorsIdRouteImport } from './routes/vendors.$id'
import { Route as ResourcesIdRouteImport } from './routes/resources.$id'
import { Route as MyFundraisersIdRouteImport } from './routes/my-fundraisers.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRosterRouteImport } from './routes/admin.roster'
import { Route as AdminReadinessRouteImport } from './routes/admin.readiness'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminPackingRouteImport } from './routes/admin.packing'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminJourneyRouteImport } from './routes/admin.journey'
import { Route as AdminGoalsRouteImport } from './routes/admin.goals'
import { Route as AdminFundraisingRouteImport } from './routes/admin.fundraising'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminFamilyRouteImport } from './routes/admin.family'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminConciergeRouteImport } from './routes/admin.concierge'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as FundraisersSlugIndexRouteImport } from './routes/fundraisers.$slug.index'
import { Route as FundraisersSlugThanksRouteImport } from './routes/fundraisers.$slug.thanks'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicSbSplatRouteImport } from './routes/api/public/sb/$'
import { Route as ApiPublicFundraisingAssetIdRouteImport } from './routes/api/public/fundraising-asset/$id'
import { Route as ApiPublicFundraiserFlierIdRouteImport } from './routes/api/public/fundraiser-flier/$id'
import { Route as ApiPublicEventFlierIdRouteImport } from './routes/api/public/event-flier/$id'
import { Route as ApiPublicBrandingKindRouteImport } from './routes/api/public/branding/$kind'
import { Route as ApiPublicAvatarUserIdRouteImport } from './routes/api/public/avatar/$userId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderProgressRoute = RiderProgressRouteImport.update({
  id: '/rider-progress',
  path: '/rider-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraiserRequestRoute = FundraiserRequestRouteImport.update({
  id: '/fundraiser-request',
  path: '/fundraiser-request',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsLoungeRoute = CaptainsLoungeRouteImport.update({
  id: '/captains-lounge',
  path: '/captains-lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFundraisersIndexRoute = MyFundraisersIndexRouteImport.update({
  id: '/my-fundraisers/',
  path: '/my-fundraisers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisersIndexRoute = FundraisersIndexRouteImport.update({
  id: '/fundraisers/',
  path: '/fundraisers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsNewRoute = VendorsNewRouteImport.update({
  id: '/vendors/new',
  path: '/vendors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResourcesRoute,
} as any)
const MyFundraisersIdRoute = MyFundraisersIdRouteImport.update({
  id: '/my-fundraisers/$id',
  path: '/my-fundraisers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRosterRoute = AdminRosterRouteImport.update({
  id: '/admin/roster',
  path: '/admin/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReadinessRoute = AdminReadinessRouteImport.update({
  id: '/admin/readiness',
  path: '/admin/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackingRoute = AdminPackingRouteImport.update({
  id: '/admin/packing',
  path: '/admin/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJourneyRoute = AdminJourneyRouteImport.update({
  id: '/admin/journey',
  path: '/admin/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGoalsRoute = AdminGoalsRouteImport.update({
  id: '/admin/goals',
  path: '/admin/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFundraisingRoute = AdminFundraisingRouteImport.update({
  id: '/admin/fundraising',
  path: '/admin/fundraising',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/admin/flags',
  path: '/admin/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFamilyRoute = AdminFamilyRouteImport.update({
  id: '/admin/family',
  path: '/admin/family',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConciergeRoute = AdminConciergeRouteImport.update({
  id: '/admin/concierge',
  path: '/admin/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const FundraisersSlugIndexRoute = FundraisersSlugIndexRouteImport.update({
  id: '/fundraisers/$slug/',
  path: '/fundraisers/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisersSlugThanksRoute = FundraisersSlugThanksRouteImport.update({
  id: '/fundraisers/$slug/thanks',
  path: '/fundraisers/$slug/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSbSplatRoute = ApiPublicSbSplatRouteImport.update({
  id: '/api/public/sb/$',
  path: '/api/public/sb/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFundraisingAssetIdRoute =
  ApiPublicFundraisingAssetIdRouteImport.update({
    id: '/api/public/fundraising-asset/$id',
    path: '/api/public/fundraising-asset/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFundraiserFlierIdRoute =
  ApiPublicFundraiserFlierIdRouteImport.update({
    id: '/api/public/fundraiser-flier/$id',
    path: '/api/public/fundraiser-flier/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEventFlierIdRoute = ApiPublicEventFlierIdRouteImport.update({
  id: '/api/public/event-flier/$id',
  path: '/api/public/event-flier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandingKindRoute = ApiPublicBrandingKindRouteImport.update({
  id: '/api/public/branding/$kind',
  path: '/api/public/branding/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvatarUserIdRoute = ApiPublicAvatarUserIdRouteImport.update({
  id: '/api/public/avatar/$userId',
  path: '/api/public/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/captains-lounge': typeof CaptainsLoungeRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/fundraiser-request': typeof FundraiserRequestRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/rider-progress': typeof RiderProgressRoute
  '/signin': typeof SigninRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/fundraising': typeof AdminFundraisingRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/journey': typeof AdminJourneyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packing': typeof AdminPackingRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/users': typeof AdminUsersRoute
  '/my-fundraisers/$id': typeof MyFundraisersIdRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/new': typeof VendorsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/fundraisers/': typeof FundraisersIndexRoute
  '/my-fundraisers/': typeof MyFundraisersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/fundraisers/$slug/thanks': typeof FundraisersSlugThanksRoute
  '/fundraisers/$slug/': typeof FundraisersSlugIndexRoute
  '/api/public/avatar/$userId': typeof ApiPublicAvatarUserIdRoute
  '/api/public/branding/$kind': typeof ApiPublicBrandingKindRoute
  '/api/public/event-flier/$id': typeof ApiPublicEventFlierIdRoute
  '/api/public/fundraiser-flier/$id': typeof ApiPublicFundraiserFlierIdRoute
  '/api/public/fundraising-asset/$id': typeof ApiPublicFundraisingAssetIdRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/captains-lounge': typeof CaptainsLoungeRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/fundraiser-request': typeof FundraiserRequestRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/rider-progress': typeof RiderProgressRoute
  '/signin': typeof SigninRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/fundraising': typeof AdminFundraisingRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/journey': typeof AdminJourneyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packing': typeof AdminPackingRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/users': typeof AdminUsersRoute
  '/my-fundraisers/$id': typeof MyFundraisersIdRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/new': typeof VendorsNewRoute
  '/admin': typeof AdminIndexRoute
  '/fundraisers': typeof FundraisersIndexRoute
  '/my-fundraisers': typeof MyFundraisersIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/fundraisers/$slug/thanks': typeof FundraisersSlugThanksRoute
  '/fundraisers/$slug': typeof FundraisersSlugIndexRoute
  '/api/public/avatar/$userId': typeof ApiPublicAvatarUserIdRoute
  '/api/public/branding/$kind': typeof ApiPublicBrandingKindRoute
  '/api/public/event-flier/$id': typeof ApiPublicEventFlierIdRoute
  '/api/public/fundraiser-flier/$id': typeof ApiPublicFundraiserFlierIdRoute
  '/api/public/fundraising-asset/$id': typeof ApiPublicFundraisingAssetIdRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/captains-lounge': typeof CaptainsLoungeRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/expenses': typeof ExpensesRoute
  '/family': typeof FamilyRoute
  '/fundraiser-request': typeof FundraiserRequestRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/messages': typeof MessagesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/rider-progress': typeof RiderProgressRoute
  '/signin': typeof SigninRoute
  '/team': typeof TeamRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/family': typeof AdminFamilyRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/fundraising': typeof AdminFundraisingRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/journey': typeof AdminJourneyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packing': typeof AdminPackingRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/users': typeof AdminUsersRoute
  '/my-fundraisers/$id': typeof MyFundraisersIdRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/new': typeof VendorsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/fundraisers/': typeof FundraisersIndexRoute
  '/my-fundraisers/': typeof MyFundraisersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/fundraisers/$slug/thanks': typeof FundraisersSlugThanksRoute
  '/fundraisers/$slug/': typeof FundraisersSlugIndexRoute
  '/api/public/avatar/$userId': typeof ApiPublicAvatarUserIdRoute
  '/api/public/branding/$kind': typeof ApiPublicBrandingKindRoute
  '/api/public/event-flier/$id': typeof ApiPublicEventFlierIdRoute
  '/api/public/fundraiser-flier/$id': typeof ApiPublicFundraiserFlierIdRoute
  '/api/public/fundraising-asset/$id': typeof ApiPublicFundraisingAssetIdRoute
  '/api/public/sb/$': typeof ApiPublicSbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/captains-lounge'
    | '/confirmation'
    | '/dashboard'
    | '/events'
    | '/expenses'
    | '/family'
    | '/fundraiser-request'
    | '/health'
    | '/mcp'
    | '/messages'
    | '/packing'
    | '/profile'
    | '/register'
    | '/resources'
    | '/rider-progress'
    | '/signin'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/branding'
    | '/admin/concierge'
    | '/admin/contacts'
    | '/admin/family'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/fundraising'
    | '/admin/goals'
    | '/admin/journey'
    | '/admin/notifications'
    | '/admin/packing'
    | '/admin/participants'
    | '/admin/readiness'
    | '/admin/roster'
    | '/admin/users'
    | '/my-fundraisers/$id'
    | '/resources/$id'
    | '/vendors/$id'
    | '/vendors/new'
    | '/admin/'
    | '/fundraisers/'
    | '/my-fundraisers/'
    | '/vendors/'
    | '/.mcp/invoke-tool/$tool'
    | '/fundraisers/$slug/thanks'
    | '/fundraisers/$slug/'
    | '/api/public/avatar/$userId'
    | '/api/public/branding/$kind'
    | '/api/public/event-flier/$id'
    | '/api/public/fundraiser-flier/$id'
    | '/api/public/fundraising-asset/$id'
    | '/api/public/sb/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/captains-lounge'
    | '/confirmation'
    | '/dashboard'
    | '/events'
    | '/expenses'
    | '/family'
    | '/fundraiser-request'
    | '/health'
    | '/mcp'
    | '/messages'
    | '/packing'
    | '/profile'
    | '/register'
    | '/resources'
    | '/rider-progress'
    | '/signin'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/branding'
    | '/admin/concierge'
    | '/admin/contacts'
    | '/admin/family'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/fundraising'
    | '/admin/goals'
    | '/admin/journey'
    | '/admin/notifications'
    | '/admin/packing'
    | '/admin/participants'
    | '/admin/readiness'
    | '/admin/roster'
    | '/admin/users'
    | '/my-fundraisers/$id'
    | '/resources/$id'
    | '/vendors/$id'
    | '/vendors/new'
    | '/admin'
    | '/fundraisers'
    | '/my-fundraisers'
    | '/vendors'
    | '/.mcp/invoke-tool/$tool'
    | '/fundraisers/$slug/thanks'
    | '/fundraisers/$slug'
    | '/api/public/avatar/$userId'
    | '/api/public/branding/$kind'
    | '/api/public/event-flier/$id'
    | '/api/public/fundraiser-flier/$id'
    | '/api/public/fundraising-asset/$id'
    | '/api/public/sb/$'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/captains-lounge'
    | '/confirmation'
    | '/dashboard'
    | '/events'
    | '/expenses'
    | '/family'
    | '/fundraiser-request'
    | '/health'
    | '/mcp'
    | '/messages'
    | '/packing'
    | '/profile'
    | '/register'
    | '/resources'
    | '/rider-progress'
    | '/signin'
    | '/team'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/branding'
    | '/admin/concierge'
    | '/admin/contacts'
    | '/admin/family'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/fundraising'
    | '/admin/goals'
    | '/admin/journey'
    | '/admin/notifications'
    | '/admin/packing'
    | '/admin/participants'
    | '/admin/readiness'
    | '/admin/roster'
    | '/admin/users'
    | '/my-fundraisers/$id'
    | '/resources/$id'
    | '/vendors/$id'
    | '/vendors/new'
    | '/admin/'
    | '/fundraisers/'
    | '/my-fundraisers/'
    | '/vendors/'
    | '/.mcp/invoke-tool/$tool'
    | '/fundraisers/$slug/thanks'
    | '/fundraisers/$slug/'
    | '/api/public/avatar/$userId'
    | '/api/public/branding/$kind'
    | '/api/public/event-flier/$id'
    | '/api/public/fundraiser-flier/$id'
    | '/api/public/fundraising-asset/$id'
    | '/api/public/sb/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CaptainsLoungeRoute: typeof CaptainsLoungeRoute
  ConfirmationRoute: typeof ConfirmationRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  ExpensesRoute: typeof ExpensesRoute
  FamilyRoute: typeof FamilyRoute
  FundraiserRequestRoute: typeof FundraiserRequestRoute
  HealthRoute: typeof HealthRoute
  McpRoute: typeof McpRoute
  MessagesRoute: typeof MessagesRoute
  PackingRoute: typeof PackingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  RiderProgressRoute: typeof RiderProgressRoute
  SigninRoute: typeof SigninRoute
  TeamRoute: typeof TeamRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminConciergeRoute: typeof AdminConciergeRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminFamilyRoute: typeof AdminFamilyRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminFundraisingRoute: typeof AdminFundraisingRoute
  AdminGoalsRoute: typeof AdminGoalsRoute
  AdminJourneyRoute: typeof AdminJourneyRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackingRoute: typeof AdminPackingRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminReadinessRoute: typeof AdminReadinessRoute
  AdminRosterRoute: typeof AdminRosterRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MyFundraisersIdRoute: typeof MyFundraisersIdRoute
  VendorsIdRoute: typeof VendorsIdRoute
  VendorsNewRoute: typeof VendorsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FundraisersIndexRoute: typeof FundraisersIndexRoute
  MyFundraisersIndexRoute: typeof MyFundraisersIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  FundraisersSlugThanksRoute: typeof FundraisersSlugThanksRoute
  FundraisersSlugIndexRoute: typeof FundraisersSlugIndexRoute
  ApiPublicAvatarUserIdRoute: typeof ApiPublicAvatarUserIdRoute
  ApiPublicBrandingKindRoute: typeof ApiPublicBrandingKindRoute
  ApiPublicEventFlierIdRoute: typeof ApiPublicEventFlierIdRoute
  ApiPublicFundraiserFlierIdRoute: typeof ApiPublicFundraiserFlierIdRoute
  ApiPublicFundraisingAssetIdRoute: typeof ApiPublicFundraisingAssetIdRoute
  ApiPublicSbSplatRoute: typeof ApiPublicSbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider-progress': {
      id: '/rider-progress'
      path: '/rider-progress'
      fullPath: '/rider-progress'
      preLoaderRoute: typeof RiderProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraiser-request': {
      id: '/fundraiser-request'
      path: '/fundraiser-request'
      fullPath: '/fundraiser-request'
      preLoaderRoute: typeof FundraiserRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains-lounge': {
      id: '/captains-lounge'
      path: '/captains-lounge'
      fullPath: '/captains-lounge'
      preLoaderRoute: typeof CaptainsLoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-fundraisers/': {
      id: '/my-fundraisers/'
      path: '/my-fundraisers'
      fullPath: '/my-fundraisers/'
      preLoaderRoute: typeof MyFundraisersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraisers/': {
      id: '/fundraisers/'
      path: '/fundraisers'
      fullPath: '/fundraisers/'
      preLoaderRoute: typeof FundraisersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/new': {
      id: '/vendors/new'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof VendorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/my-fundraisers/$id': {
      id: '/my-fundraisers/$id'
      path: '/my-fundraisers/$id'
      fullPath: '/my-fundraisers/$id'
      preLoaderRoute: typeof MyFundraisersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roster': {
      id: '/admin/roster'
      path: '/admin/roster'
      fullPath: '/admin/roster'
      preLoaderRoute: typeof AdminRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/readiness': {
      id: '/admin/readiness'
      path: '/admin/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AdminReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packing': {
      id: '/admin/packing'
      path: '/admin/packing'
      fullPath: '/admin/packing'
      preLoaderRoute: typeof AdminPackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journey': {
      id: '/admin/journey'
      path: '/admin/journey'
      fullPath: '/admin/journey'
      preLoaderRoute: typeof AdminJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/goals': {
      id: '/admin/goals'
      path: '/admin/goals'
      fullPath: '/admin/goals'
      preLoaderRoute: typeof AdminGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fundraising': {
      id: '/admin/fundraising'
      path: '/admin/fundraising'
      fullPath: '/admin/fundraising'
      preLoaderRoute: typeof AdminFundraisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/admin/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/family': {
      id: '/admin/family'
      path: '/admin/family'
      fullPath: '/admin/family'
      preLoaderRoute: typeof AdminFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/concierge': {
      id: '/admin/concierge'
      path: '/admin/concierge'
      fullPath: '/admin/concierge'
      preLoaderRoute: typeof AdminConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraisers/$slug/': {
      id: '/fundraisers/$slug/'
      path: '/fundraisers/$slug'
      fullPath: '/fundraisers/$slug/'
      preLoaderRoute: typeof FundraisersSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraisers/$slug/thanks': {
      id: '/fundraisers/$slug/thanks'
      path: '/fundraisers/$slug/thanks'
      fullPath: '/fundraisers/$slug/thanks'
      preLoaderRoute: typeof FundraisersSlugThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sb/$': {
      id: '/api/public/sb/$'
      path: '/api/public/sb/$'
      fullPath: '/api/public/sb/$'
      preLoaderRoute: typeof ApiPublicSbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fundraising-asset/$id': {
      id: '/api/public/fundraising-asset/$id'
      path: '/api/public/fundraising-asset/$id'
      fullPath: '/api/public/fundraising-asset/$id'
      preLoaderRoute: typeof ApiPublicFundraisingAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fundraiser-flier/$id': {
      id: '/api/public/fundraiser-flier/$id'
      path: '/api/public/fundraiser-flier/$id'
      fullPath: '/api/public/fundraiser-flier/$id'
      preLoaderRoute: typeof ApiPublicFundraiserFlierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event-flier/$id': {
      id: '/api/public/event-flier/$id'
      path: '/api/public/event-flier/$id'
      fullPath: '/api/public/event-flier/$id'
      preLoaderRoute: typeof ApiPublicEventFlierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/branding/$kind': {
      id: '/api/public/branding/$kind'
      path: '/api/public/branding/$kind'
      fullPath: '/api/public/branding/$kind'
      preLoaderRoute: typeof ApiPublicBrandingKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatar/$userId': {
      id: '/api/public/avatar/$userId'
      path: '/api/public/avatar/$userId'
      fullPath: '/api/public/avatar/$userId'
      preLoaderRoute: typeof ApiPublicAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesIdRoute: typeof ResourcesIdRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesIdRoute: ResourcesIdRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CaptainsLoungeRoute: CaptainsLoungeRoute,
  ConfirmationRoute: ConfirmationRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  ExpensesRoute: ExpensesRoute,
  FamilyRoute: FamilyRoute,
  FundraiserRequestRoute: FundraiserRequestRoute,
  HealthRoute: HealthRoute,
  McpRoute: McpRoute,
  MessagesRoute: MessagesRoute,
  PackingRoute: PackingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  RiderProgressRoute: RiderProgressRoute,
  SigninRoute: SigninRoute,
  TeamRoute: TeamRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminConciergeRoute: AdminConciergeRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminFamilyRoute: AdminFamilyRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminFundraisingRoute: AdminFundraisingRoute,
  AdminGoalsRoute: AdminGoalsRoute,
  AdminJourneyRoute: AdminJourneyRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackingRoute: AdminPackingRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminReadinessRoute: AdminReadinessRoute,
  AdminRosterRoute: AdminRosterRoute,
  AdminUsersRoute: AdminUsersRoute,
  MyFundraisersIdRoute: MyFundraisersIdRoute,
  VendorsIdRoute: VendorsIdRoute,
  VendorsNewRoute: VendorsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  FundraisersIndexRoute: FundraisersIndexRoute,
  MyFundraisersIndexRoute: MyFundraisersIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  FundraisersSlugThanksRoute: FundraisersSlugThanksRoute,
  FundraisersSlugIndexRoute: FundraisersSlugIndexRoute,
  ApiPublicAvatarUserIdRoute: ApiPublicAvatarUserIdRoute,
  ApiPublicBrandingKindRoute: ApiPublicBrandingKindRoute,
  ApiPublicEventFlierIdRoute: ApiPublicEventFlierIdRoute,
  ApiPublicFundraiserFlierIdRoute: ApiPublicFundraiserFlierIdRoute,
  ApiPublicFundraisingAssetIdRoute: ApiPublicFundraisingAssetIdRoute,
  ApiPublicSbSplatRoute: ApiPublicSbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
